force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Claim</relationshipLabel>
    <relationshipName>Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Policy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Policy_State__c.field-meta.xml
<CustomField>
    <fullName>Policy_State__c</fullName>
    <label>Policy State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InsuranceDashboardController.cls
public with sharing class InsuranceDashboardController {

    @AuraEnabled
    public static Integer getPolicyCount() {
        return [SELECT COUNT() FROM Policy__c];
    }

    @AuraEnabled
    public static Integer getClaimCount() {
        return [SELECT COUNT() FROM Claim__c];
    }
    @AuraEnabled
    public static Decimal getTotalPremium() {
        AggregateResult result = [
            SELECT SUM(Premium__c) totalPremium
            FROM Policy__c
        ];

        Decimal totalPremium = (Decimal) result.get('totalPremium');

        return totalPremium == null ? 0 : totalPremium;
    }
    @AuraEnabled
    public static Decimal getTotalClaimAmount() {
        AggregateResult result = [
            SELECT SUM(Claim_Amount__c) totalClaimAmount
            FROM Claim__c
        ];

        Decimal totalClaimAmount = (Decimal) result.get('totalClaimAmount');

        return totalClaimAmount == null ? 0 : totalClaimAmount;
    }
    @AuraEnabled
    public static List<Policy__c> getPolicies() {
        return [
            SELECT Id, Name, Premium__c, Policy_Start_Date__c, Policy_State__c
            FROM Policy__c
            ORDER BY CreatedDate DESC
            LIMIT 5
        ];
    }
    @AuraEnabled
public static List<Claim__c> getClaims() {
    return [
        SELECT Id, Name, Claim_Amount__c, Approval_Status__c, Policy__c
        FROM Claim__c
        ORDER BY CreatedDate DESC
        LIMIT 5
    ];
}
    @AuraEnabled
public static Map<String, Integer> getClaimStatusCounts() {

    Map<String, Integer> statusCounts = new Map<String, Integer>();

    statusCounts.put('New', 0);
    statusCounts.put('SubmittedForApproval', 0);
    statusCounts.put('Approved', 0);
    statusCounts.put('Rejected', 0);

    for (AggregateResult result : [
        SELECT Approval_Status__c status, COUNT(Id) total
        FROM Claim__c
        GROUP BY Approval_Status__c
    ]) {

        String status = (String) result.get('status');
        Integer total = (Integer) result.get('total');

        if (status == null || status == '') {
            statusCounts.put(
                'New',
                statusCounts.get('New') + total
            );
        }
        else if (status == 'New') {
            statusCounts.put('New', total);
        }
        else if (status == 'Submitted for Approval') {
            statusCounts.put('SubmittedForApproval', total);
        }
        else if (status == 'Approved') {
            statusCounts.put('Approved', total);
        }
        else if (status == 'Rejected') {
            statusCounts.put('Rejected', total);
        }
    }
    return statusCounts;
}
}